# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Wi-fi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(170, 60, 280, 384))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scanNetworks = QtWidgets.QPushButton(self.widget)
        self.scanNetworks.setObjectName("scanNetworks")
        self.verticalLayout.addWidget(self.scanNetworks)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.wifiListWidget = QtWidgets.QListWidget(self.widget)
        self.wifiListWidget.setObjectName("wifiListWidget")
        item = QtWidgets.QListWidgetItem()
        self.wifiListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.wifiListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.wifiListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.wifiListWidget.addItem(item)
        self.gridLayout.addWidget(self.wifiListWidget, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.selectLabel = QtWidgets.QLabel(self.widget)
        self.selectLabel.setObjectName("selectLabel")
        self.verticalLayout.addWidget(self.selectLabel, 0, QtCore.Qt.AlignHCenter)
        self.passwordLabel = QtWidgets.QLabel(self.widget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.verticalLayout.addWidget(self.passwordLabel, 0, QtCore.Qt.AlignHCenter)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.widget)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.verticalLayout.addWidget(self.passwordLineEdit)
        self.connectPushButton = QtWidgets.QPushButton(self.widget)
        self.connectPushButton.setObjectName("connectPushButton")
        self.verticalLayout.addWidget(self.connectPushButton)
        self.connectionLabel = QtWidgets.QLabel(self.widget)
        self.connectionLabel.setObjectName("connectionLabel")
        self.verticalLayout.addWidget(self.connectionLabel)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.scanNetworks.setText(_translate("MainWindow", "Scan Networks"))
        __sortingEnabled = self.wifiListWidget.isSortingEnabled()
        self.wifiListWidget.setSortingEnabled(False)
        item = self.wifiListWidget.item(0)
        item.setText(_translate("MainWindow", "Wi-fi 1"))
        item = self.wifiListWidget.item(1)
        item.setText(_translate("MainWindow", "Wi-fi 2"))
        item = self.wifiListWidget.item(2)
        item.setText(_translate("MainWindow", "Wi-fi 3"))
        item = self.wifiListWidget.item(3)
        item.setText(_translate("MainWindow", "Wi-fi 4"))
        self.wifiListWidget.setSortingEnabled(__sortingEnabled)
        self.selectLabel.setText(_translate("MainWindow", "\"Select wi-fi for connection.\""))
        self.passwordLabel.setText(_translate("MainWindow", "\"Enter password below.\""))
        self.passwordLineEdit.setText(_translate("MainWindow", "\"Enter Wi-Fi password\""))
        self.connectPushButton.setText(_translate("MainWindow", "Connect"))
        self.connectionLabel.setText(_translate("MainWindow", "Connect successfully."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
